### PR TITLE
Add Podfile version 

### PR DESCRIPTION
**Pull request by atomassoni**

### CODE REVIEW

**Comment by atomassoni** [comment]
I believe the Podfile update won't have an effect, but the podspec will.

**Review by gdburky — APPROVED** [review]

**Review by sofizambrano — APPROVED** [review]

**Review by CarlosMoraRoa — APPROVED** [review]

**Review by famaranon — APPROVED** [review]

**Comment by spaghettiguru** [comment]
Can somebody merge it please?

**Comment by famaranon** [comment]
Only maintainers are allowed to do this @atomassoni @StewanSilva

**Comment by stewones** [comment]
Going to review this weekend, sorry guys. I will try to improve docs on how to build plugin locally so y'all don't need to necessarily depende on an official release.

**Pull request merged**
