### PR TITLE
Upgrade to Capacitor v5

### PR DESCRIPTION
**Pull request by cwoebker**
Since Capacitor v5 was released I followed the instructions over at https://capacitorjs.com/docs/updating/plugins/5-0 in order to resolve this issue: #85

I checked the example project as well and realized that it was not updated since Capacitor v3. Therefore, I did not touch it.

I did verify that the plugin works correctly on Capacitor v5 with our own application. 

Let me know, if I forgot something or you have additional feedback. Thanks for maintaining this!

### CODE REVIEW

**Review by vaimor-LB — APPROVED** [review]

**Comment by mamccr** [comment]
This is fantastic! Any idea when these changes might get merged and published?

**Comment by vaimor-LB** [comment]
+1 to @mamccr's comment. Could we please have these changes merged and published ?

**Comment by kevinfavv** [comment]
Thanks ! waiting for merge...

**Comment by stewones** [comment]
released under v5

thank you!

**Pull request merged**
