### PR TITLE
feat(): update to v4

### PR DESCRIPTION
**Pull request by rdlabo**
By using `next` tag, This plugin can try to test on Capacitor 4.

```
% npm install @capacitor-community/intercom@next
```

https://github.com/capacitor-community/intercom/releases/tag/v4.0.0-0

However, this update was done automatically by `@rdlabo/capacitor-plugin-to-v4 ` ,and has not been confirmed to work. 

https://github.com/rdlabo-team/capacitor-plugin-to-v4

If you have any problems using it, please comment on this thread.

@maintainer Released with next tag to make the world compatible with Capacitor v4. Please check out this pull request and decide if you want to merge or not. Thanks for all your great work, and we look forward to working with you in the future.

### CODE REVIEW

**Comment by brennanbatalla** [comment]
Hi,

For android this branch works pretty well. No issues so far. For IOS though, looks like intercom has some updated methods that this branch has not accounted for. My ios app is unable to build do to issue shown in this screen shot:

Screen Shot 2022-09-20 at 8 10 44 PM

**Comment by cmatija-ergon** [comment]
We have encountered the very same issue. The problem is that the highlighted methods above have been deprecated, and deleted in Intercom 13.0.0. Specifying the exact version of Intercom to be used in CapacitorCommunityIntercom.podspec (e.g. 12.4.3) fixed it for us. This can be done as follows:

`s.dependency 'Intercom', '12.4.3'`

**Comment by brennanbatalla** [comment]
Thanks @cmatija-ergon, that did the trick!

**Comment by mfranzs** [comment]
We're getting this warning on V4 - do you know how we can fix? Thanks!

```
      Capacitor WebPlugin "Intercom" config object was deprecated in v3 and will be removed in v4.
    > 1 | import { Intercom } from '@capacitor-community/intercom';
```

**Pull request merged**
