### PR TITLE
Add displayCarousel API

### PR DESCRIPTION
**Pull request by adamduren**

### CODE REVIEW

**Comment by stewones** [comment]
hey Thanks for the PR. I'll try and merge soon.

**Comment by adamduren** [comment]
@stewones thank you. I didn't see a contributing document so please let me know if there's anything in the code, commit format, etc that you would like changed.

**Comment by adamduren** [comment]
@stewones any updates?

**Comment by stewones** [comment]
hey @adamdbradley sorry for delay. can you resolve conflicts and update this PR? 
Thank you

**Comment by stewones** [comment]
hey @adamduren sorry for delay. can you resolve conflicts and update this PR?
Thank you

**Comment by adamduren** [comment]
@stewones I could make this update tomorrow. Any idea when this Plugin will support v3?

**Comment by stewones** [comment]
@adamduren by the end of month yes, we're planning a big update at work which will require capacitor v3. So i'm willing to take this effort not only for this plugin

**Comment by asangadev** [comment]
> @stewones I could make this update tomorrow. Any idea when this Plugin will support v3?

Try this: https://github.com/Fiksuruoka-fi/capacitor-intercom

**Pull request merged**
